{% set name = "diceware" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 54b690809f0c56ab3085a18e15a0c3804d4a0d127f38aef0b5cf5f859d0f6639

build:
  noarch: python
  number: 0
  entry_points:
    - diceware = diceware:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools

test:
  imports:
    - diceware
  commands:
    - diceware --help
  requires:
    - coverage
    - pytest >=2.8.3

about:
  home: https://pypi.org/project/diceware/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "Passphrases you will remember."
  doc_url: https://diceware.readthedocs.io/en/stable/
  dev_url: https://github.com/ulif/diceware

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
    - RyanHackney
